### ISSUE TITLE
KeyError: 'pageno'

### ISSUE THREAD

**Issue by mfauvain** [friciwolf/XournalppUtils#1]
Hello, thx for the script, not working here, with the below error. Can you help?
```
Traceback (most recent call last):
  File "/.../XournalppUtils.py", line 50, in <module>
    pageNb = elements[0].attrib["pageno"]
KeyError: 'pageno'
```

Thx

**Comment by friciwolf** [comment]
Hi!
Looking into the problem a bit, I have found that a background needs to be set in the xopp-file in order to make the missing attribute appear.
Hope this helps,  cheers!
